# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1137ae580bdc86f5a543bad5e29548a0c61746a161b8532de5c0ddc07faeb4b95546e4b765e597bed2e96ffaa8659576a2da2379d5143be055ed2450af829a6e

test:
  secret_key_base: be79e0acb2f1d0ed20ffc61b1e797f397049a949a3327bb55d6465c3026a7acf169737c6eb01ddd10c8344f038399c02d75a8bc1c81748b805448e5ca4033c82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
